//alert("Ola Mundo")
//prompt ("Quantos anos voçê tem?")
//idade = parseInt(prompt("Quantos anos você tem?"))
//alert(idade)
//var valorEmDolar = promp("Qual valor em dolar que você quer converter?")
//var valorEmReal = ValorEmDolarNumero * 5.50
//var valoremRealDecimal = valorEmReal.toFixed(2)

var dolar = parseFloat(prompt("Qual valor em dolar que você quer converter?"))
var real = dolar * 5.50
var realToFixed = real.toFixed(2)

alert(realToFixed)


